linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/senseyman/bitcoin-handshake
  gocyclo:
    min-complexity: 20
  misspell:
    locale: US
  dupl:
    threshold: 100

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - gocyclo
    - misspell
    - dupl
    - unconvert
    - ineffassign
    - errcheck
    - staticcheck
    - unused
    - typecheck

issues:
  exclude-rules:
    - text: "weak cryptographic primitive"
      linters:
        - gosec
    - path: _test\.go
      linters:
        - govet
        - dupl

output:
  print-issued-lines: true
  print-linter-name: true
